spring:
  datasource:
    url: jdbc:mysql://118.184.29.81:3306/meteorlight?useSSL=false&serverTimezone=UTC
    # url: jdbc:mysql://118.184.29.81:3306/meteorlight?useSSL=false&serverTimezone=UTC
    username: latesum
    password: 7vqKxCMQS7nScDJf
    driverClassName: com.mysql.cj.jdbc.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    # Specify the DBMS
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
    # stripped before adding them to the entity manager)
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  session:
    store-type: redis
  mail:
    host: smtp.exmail.qq.com
    username: dev@pat-edu.com
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    password: SBSpring123
  http:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
server:
  compression:
    enabled: true
    mime-types: text/plain,text/css,application/json,application/javascript,text/xml,application/xml,application/xml+rss,text/javascript
redis:
  host: 118.184.29.81
  port: 6379
  password: 9Klv4f7RgXJ2rnSQ
validator:
  login:
    protection: true
security:
  basic:
    enabled: false
